GET http://localhost:3000/users

'localhost:3000/users'


### 

GET http://localhost:3000/users/5f7f8278b4bf2a2064ee9505


#### 

POST http://localhost:3000/users
 Content-Type: application/json


 {
     "name": "Che Coelho",
     "alias": "CheTC",
     "password": "CTC",
     "email": "checoelho@gmail.com",
     "creditLimit": -200,
     "currentBalance": 0,
     "totalSpent": 0,
     "totalEarned": 0, 
     "participation": 0,
     "spendingCapacity": 200
 }


### 


DELETE http://localhost:3000/users/5f7f7f057c55492608afafc3

### 

PATCH http://localhost:3000/users/5f7f32be4218de2b94f54f74
Content-Type: application/json

{
    "name": "New name"
}

###

GET http://localhost:3000/home

'localhost:3000/users'


### 


GET http://localhost:3000/users/:id



###
//login test
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "checoelho@gmail.com",
    "password": "cc"
}

###
//login auth for home

POST http://localhost:3000/users/home


### 